spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/liming495/seat/
          searchPaths: config-repo
server:
  port: 8888