server:
  port: 8761

eureka:
  instance:
    hostname: node1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://node2:${server.port}/eureka/
spring:
  application:
    name: registry
  profiles: node1